name: ai_flutter_assistant
description: AI Assistant + Python Executor + Flutter Docs
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  provider: ^6.1.2

flutter:
  uses-material-design: true
